version: "3.8"
services:
  postgres:
    container_name: postgres_blog_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres:/data/postgres

    ports:
      - "5432:5432"
volumes:
  postgres:
    driver: local